name: Docker Image CI

on:
  push:
    branches:
    - release/*

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: Jtav1/sharex-custom-server@latest
    - name: Build the Docker image
    - run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
